[package]
name = "fp"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
fp-rust = { path = "crates/fp-rust" }

[workspace]
resolver = "2"
members = [
    "crates/*",
]
default-members = ["crates/fp-cli"]
