[package]
name = "fp"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
fp-rust = { path = "crates/fp-rust" }

[dev-dependencies]
criterion = "0.8"


[workspace]
resolver = "2"
members = [
    "crates/*",
]
default-members = ["crates/fp-cli"]
