[package]
name = "fp-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
fp-core = { path = "../fp-core" }
fp-backend = { path = "../fp-backend" }
eyre = "0.6"
thiserror = "2.0.17"
winnow = "0.6"
tracing = "0.1"
bigdecimal = "0.4"
num-bigint = "0.4"
